BLOCK_SIZE: int = 2 * 1024  # * 1024  # * 1024
THRESHOLD: int = 16 * 1024 * 1024 * 1024
MEMORY_LIMIT: int = 1024  # * 3
BUILDED_INDEX_PATH: str = "data/builded_index/"
FINAL_INDEX_PATH: str = "data/files_index/"
BERT_DATA_PATH: str = "data/bert_processed/"
TOP_CUT: int = 5
MAX_LEN_BERT: int = 512
DATA_PATH: str = "wiki_movie_plots_deduped.csv"
DATA_PATH2: str = "wiki_movie_plots_deduped2.csv"
KEYWORDS: set = {"and", "or", "not", "andnot", "ornot"}
